version: '3.3'

services:
  web:
    build: ./test_task
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test_task/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
