# Generated by Django 3.0.5 on 2020-04-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200418_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
    ]
