# Generated by Django 3.0.5 on 2020-04-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='api.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='api.Currency'),
        ),
    ]
