# Generated by Django 3.0.5 on 2020-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_currency_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['id']},
        ),
    ]
