# Generated by Django 3.0.5 on 2020-04-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200418_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name']},
        ),
    ]
